export const data = [
  {
    id: 1,
    url: "anime-boy-dark.jpeg",
    alt: "An animated boy with neon light horns",
    tag: "anime",
  },
  {
    id: 2,
    url: "anime-boy-with-mask.webp",
    alt: "An animated boy wearing a mask",
    tag: "anime",
  },
  {
    id: 3,
    url: "background-1.jpeg",
    alt: "A laptop background",
    tag: "background",
  },
  {
    id: 4,
    url: "background-2.jpeg",
    alt: "A shed in the wilderness",
    tag: "background",
  },
  {
    id: 5,
    url: "books-1.avif",
    alt: "A stack of books",
    tag: "book",
  },
  {
    id: 6,
    url: "books-3.webp",
    alt: "An open book with words hovering around it",
    tag: "book",
  },
  {
    id: 7,
    url: "boy-with-blue-eyes.jpeg",
    alt: "An animated boy with bright blue eyes",
    tag: "anime",
  },
  {
    id: 8,
    url: "games-1.avif",
    alt: "A game console pad",
    tag: "game",
  },
  {
    id: 9,
    url: "games-3.jpeg",
    alt: "A group of game characters",
    tag: "game",
  },
  {
    id: 10,
    url: "goth-anime-girl.jpeg",
    alt: "An animated goth girl",
    tag: "anime",
  },
  {
    id: 11,
    url: "laptop-1.jpeg",
    alt: "A laptop",
    tag: "laptop",
  },
  {
    id: 12,
    url: "mirror-anime-boy.jpeg",
    alt: "An animated boy posing in front of a mirror",
    tag: "anime",
  },
  {
    id: 13,
    url: "nature-1.jpeg",
    alt: "Green landscape with flowers and trees",
    tag: "nature",
  },
  {
    id: 14,
    url: "nature-2.avif",
    alt: "A stream",
    tag: "nature",
  },
  {
    id: 15,
    url: "nature-3.jpeg",
    alt: "Green landscape",
    tag: "nature",
  },
  {
    id: 16,
    url: "nature-5.jpeg",
    alt: "Middle of a forest",
    tag: "nature",
  },
  {
    id: 17,
    url: "staring-anime-boy.jpeg",
    alt: "An animated boy staring at someone",
    tag: "anime",
  },
];
